version: 1.0.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  verbosity: minimal
notifications:
- provider: Slack
  incoming_webhook:
    secure: Mtm90XxM7T+5NlCQZ6xlQMqJ4I88JWmn6Vf3CgsTmhmcWPZHzIX5v5UxiOxtXqlpqWYVaXLCBsxU3vCMw+Ru9rhtrVag0a9ZvTzg59uU4KM=
artifacts:
- path: src\bin\Debug\RedBear.MpanGenerator.exe
